server.port=8080

spring.sqlite.database.path=./music-server.db

music.storage.path=F:/音乐文件
music.temp.path=./music-storage/temp

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

admin.username=admin
admin.password=admin123
